# Generated by Django 5.1.3 on 2024-11-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_count',
            new_name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
